services:
  # Backend: Laravel
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyxis-admin
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pyxis_db
      - DB_USERNAME=pyxis_user
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - pyxis-network

  # Database: PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: pyxis-db
    environment:
      - POSTGRES_DB=pyxis_db
      - POSTGRES_USER=pyxis_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pyxis-network

  db-panel:
    image: adminer
    container_name: pyxis-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - pyxis-network

volumes:
  db_data:

networks:
  pyxis-network:
    external: true